# Generated by Django 4.2.17 on 2025-01-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_article_dislikes_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_added',
        ),
    ]
